class TaskList < ActiveRecord::Migration
  def self.up
Task.create(:name =>'Teamil on nimi ja robotil on nimi', :display_order =>1)
Task.create(:name =>'Võistlusmäärused on läbi loetud', :display_order =>2)
Task.create(:name =>'Teamil on isiklik nimeline karp oma asjade hoidmiseks', :display_order =>3)
Task.create(:name =>'Teamil on teamisisene regulaarne kokkusaamine paigas', :display_order =>4)
Task.create(:name =>'Teamil on visioon pallide ja värava leidmisest', :display_order =>5)
Task.create(:name =>'Teamil on tiimileht wikis', :display_order =>6)
Task.create(:name =>'Teamil on kere kohta idee', :display_order =>7)
Task.create(:name =>'Teamil on mikrokontrolleri trükiplaat', :display_order =>8)
Task.create(:name =>'Teamil on mikrokontroller joodetud ja testitud', :display_order =>9)
Task.create(:name =>'Teamil on programmaator (valmis ja testitud)', :display_order =>10)
Task.create(:name =>'Teamil on palli löömise prototüüp', :display_order =>11)
Task.create(:name =>'Robotil on kere koos ratastega', :display_order =>12)
Task.create(:name =>'Robotil on mootorid kere küljes', :display_order =>13)
Task.create(:name =>'Robotil on mikroprotsessorid küljes', :display_order =>14)
Task.create(:name =>'Robotil on plaat pistikute, toitejuhtmete ja masside ühendamiseks', :display_order =>15)
Task.create(:name =>'Robotil on mootori driverid küljes (kui on vaja)', :display_order =>16)
Task.create(:name =>'Robotil on dokumentatsioon', :display_order =>17)
Task.create(:name =>'Teamil on nimekiri asjadest, mida on vaja osta enne võistlust', :display_order =>18)
Task.create(:name =>'Robotil on andurid ja lülitid küljes', :display_order =>19)
Task.create(:name =>'Robotil on akud küljes', :display_order =>20)
Task.create(:name =>'Teamil on akulaadija ja akude varu ja inimene, kes vastutab akude eest', :display_order =>21)
Task.create(:name =>'Robotil on süsteem akude täituvuse jälgimiseks (kõik akud)', :display_order =>22)
Task.create(:name =>'Robot on programmeeritav', :display_order =>23)
Task.create(:name =>'Roboti mootorid on MPSi poolt juhitavad', :display_order =>24)
Task.create(:name =>'Roboti andurid ja lülitid on MPSi poolt loetavad', :display_order =>25)
Task.create(:name =>'Roboti manipulaatorid on MPSi poolt juhitavad', :display_order =>26)
Task.create(:name =>'Robotil on programm liikumiseks ja seinade vältimiseks', :display_order =>27)
Task.create(:name =>'Robotil on lahtised ja lotendavad juhtmed hästi ära paigutatud', :display_order =>28)
Task.create(:name =>'Roboti on kaitsevest seljas (vastase roboti vastu)', :display_order =>29)
Task.create(:name =>'Juhtmed on märgistatud', :display_order =>30)
Task.create(:name =>'Palli löömise mehanism kere küljes', :display_order =>31)
Task.create(:name =>'Teami on asus kere küljes', :display_order =>32)
Task.create(:name =>'Teamil suhtleb asus mikrokontrolleriga', :display_order =>33)
Task.create(:name =>'MPS programm on valmis', :display_order =>34)
Task.create(:name =>'Robot leiab palli(d)', :display_order =>35)
Task.create(:name =>'Robot leiab värava(d) infra abil', :display_order =>36)
Task.create(:name =>'Robot leiab värava(d) värvi abil', :display_order =>37)
Task.create(:name =>'Robot tuvastab vastase roboti (kaamera)', :display_order =>38)
Task.create(:name =>'Robot oskab leitud palli väravasse lüüa', :display_order =>39)
Task.create(:name =>'Robot saab palli seinast kätte', :display_order =>40)
Task.create(:name =>'Robot saab palli nurgast kätte', :display_order =>41)
Task.create(:name =>'Robot suudab püüda liikuvat palli', :display_order =>42)
Task.create(:name =>'Robot väldib vastase robotit', :display_order =>43)
Task.create(:name =>'Robot kannatab välja vastase roboti rammimise.', :display_order =>44)
Task.create(:name =>'Robotil on lolli väravavahi jaoks algoritm', :display_order =>45)
Task.create(:name =>'Robotil on liikuva väravavahi jaoks algoritm', :display_order =>46)
Task.create(:name =>'Robotil on penalti kood', :display_order =>47)
Task.create(:name =>'Roboti programm on testitud', :display_order =>48)
Task.create(:name =>'Programm on testitud erinevate asetuste ja valgustingimustega', :display_order =>49)
Task.create(:name =>'Andurite testimise programm', :display_order =>50)
Task.create(:name =>'Täiturite testimise programm', :display_order =>51)
Task.create(:name =>'Robot on testitud', :display_order =>52)
Task.create(:name =>'Robotil on iseloom kah', :display_order =>53)

  end

  def self.down
  end
end
